all: myls mysearch mystat mytail

myls: myls-reyes.c
	gcc -o myls myls-reyes.c
mysearch: mysearch-reyes.c
	gcc -o mysearch mysearch-reyes.c
mystat: mystat-reyes.c
	gcc -o mystat mystat-reyes.c
mytail: mytail-reyes.c
	gcc -o mytail mytail-reyes.c
clean:
	rm -f *.o myls mysearch mystat mytail
